export type ItemCondition = 'Excellent' | 'Good' | 'Fair' | 'Like New';
export type ItemAvailability = 'Available' | 'Reserved' | 'Claimed' | 'Pending';
export type DonorType = 'Family Donor' | 'Student Donor' | 'Community Member' | 'Corporate Donor' | 'Faculty';
export type PickupType = 'Mission Arlington' | 'Curbside' | 'Scheduled';

export interface InventoryItem {
  id: string;
  name: string;
  category: string;
  condition: ItemCondition;
  description: string;
  location: string;
  availability: ItemAvailability;
  pickupType: PickupType;
  dimensions: string;
  color: string;
  donorType: DonorType;
  postedDate: string;
  expiryDate: string;
  tags: string[];
  views: number;
  requests: number;
  images: string[];
}

export const CATEGORIES = [
  'All',
  'Sofas',
  'Chairs',
  'Tables',
  'Computer Chairs',
  'Beds',
  'Bed Frames',
  'Mattresses',
  'Couches',
  'Televisions',
  'Kitchen Items',
  'Study Desks',
  'Storage',
  'Lamps',
  'Toys',
  'Bookshelves',
  'Mirrors',
  'Rugs',
  'Appliances',
  'Miscellaneous',
];

const LOCATIONS = [
  'Mission Arlington - Main Building',
  'Mission Arlington - Warehouse',
  'UTA Campus - Student Center',
  'Arlington Community Center',
  'Mission Arlington - Drop-off Point',
];

export const INVENTORY: InventoryItem[] = [
  {
    id: '1',
    name: 'Brown Leather Sofa',
    category: 'Sofas',
    condition: 'Good',
    description: 'Comfortable 3-seater brown leather sofa. Minor scuffs on armrests. Great for a student apartment living room.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '84"W x 36"D x 34"H',
    color: 'Brown',
    donorType: 'Family Donor',
    postedDate: '2025-03-15',
    expiryDate: '2025-04-15',
    tags: ['student-friendly', 'apartment', 'lightly-used'],
    views: 142,
    requests: 5,
    images: ['sofa1', 'sofa2'],
  },
  {
    id: '2',
    name: 'IKEA Study Desk',
    category: 'Study Desks',
    condition: 'Like New',
    description: 'White IKEA MICKE desk with drawer. Perfect for students. Only used for one semester.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '41"W x 20"D x 30"H',
    color: 'White',
    donorType: 'Student Donor',
    postedDate: '2025-03-20',
    expiryDate: '2025-04-20',
    tags: ['dorm-ready', 'compact', 'student-friendly', 'free'],
    views: 89,
    requests: 8,
    images: ['desk1'],
  },
  {
    id: '3',
    name: 'Queen Bed Frame',
    category: 'Bed Frames',
    condition: 'Good',
    description: 'Solid wood queen bed frame with headboard. Easy to assemble. Missing one bolt (easily replaceable).',
    location: LOCATIONS[1],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '62"W x 84"L x 48"H',
    color: 'Natural Wood',
    donorType: 'Family Donor',
    postedDate: '2025-03-10',
    expiryDate: '2025-04-10',
    tags: ['apartment', 'lightly-used'],
    views: 203,
    requests: 12,
    images: ['bedframe1', 'bedframe2'],
  },
  {
    id: '4',
    name: 'Ergonomic Computer Chair',
    category: 'Computer Chairs',
    condition: 'Good',
    description: 'Black mesh ergonomic chair with lumbar support. Height adjustable. Great for long study sessions.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '26"W x 26"D x 45"H',
    color: 'Black',
    donorType: 'Corporate Donor',
    postedDate: '2025-03-22',
    expiryDate: '2025-04-22',
    tags: ['student-friendly', 'compact', 'dorm-ready'],
    views: 178,
    requests: 15,
    images: ['chair1'],
  },
  {
    id: '5',
    name: '32" Samsung TV',
    category: 'Televisions',
    condition: 'Good',
    description: 'Samsung 32-inch LED TV. Works perfectly. Comes with remote. HDMI ports all functional.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '28"W x 16"H x 3"D',
    color: 'Black',
    donorType: 'Community Member',
    postedDate: '2025-03-18',
    expiryDate: '2025-04-18',
    tags: ['free', 'student-friendly', 'apartment'],
    views: 312,
    requests: 22,
    images: ['tv1'],
  },
  {
    id: '6',
    name: 'Wooden Bookshelf',
    category: 'Bookshelves',
    condition: 'Good',
    description: '5-shelf wooden bookcase. Dark brown finish. Holds up to 300 lbs total. Great for books and decor.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '32"W x 12"D x 72"H',
    color: 'Dark Brown',
    donorType: 'Family Donor',
    postedDate: '2025-03-12',
    expiryDate: '2025-04-12',
    tags: ['apartment', 'student-friendly'],
    views: 95,
    requests: 4,
    images: ['bookshelf1'],
  },
  {
    id: '7',
    name: 'Full Mattress',
    category: 'Mattresses',
    condition: 'Good',
    description: 'Clean full-size mattress. No stains. Sanitized. Great for a student apartment bedroom.',
    location: LOCATIONS[1],
    availability: 'Reserved',
    pickupType: 'Scheduled',
    dimensions: '54"W x 75"L x 9"H',
    color: 'White',
    donorType: 'Family Donor',
    postedDate: '2025-03-08',
    expiryDate: '2025-04-08',
    tags: ['apartment', 'urgent-pickup'],
    views: 275,
    requests: 19,
    images: ['mattress1'],
  },
  {
    id: '8',
    name: 'Kitchen Utensil Set',
    category: 'Kitchen Items',
    condition: 'Like New',
    description: 'Complete 20-piece kitchen utensil set in stainless steel. Includes spatulas, ladles, tongs, and more.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: 'Standard',
    color: 'Silver/Black',
    donorType: 'Community Member',
    postedDate: '2025-03-25',
    expiryDate: '2025-04-25',
    tags: ['compact', 'dorm-ready', 'student-friendly', 'free'],
    views: 67,
    requests: 6,
    images: ['utensils1'],
  },
  {
    id: '9',
    name: 'Floor Lamp',
    category: 'Lamps',
    condition: 'Like New',
    description: 'Modern brushed nickel floor lamp, 60-inch tall. Works with standard bulbs. Great ambient lighting.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '60"H x 10" base',
    color: 'Silver',
    donorType: 'Student Donor',
    postedDate: '2025-03-23',
    expiryDate: '2025-04-23',
    tags: ['compact', 'dorm-ready', 'apartment'],
    views: 54,
    requests: 3,
    images: ['lamp1'],
  },
  {
    id: '10',
    name: 'Area Rug 5x7',
    category: 'Rugs',
    condition: 'Good',
    description: 'Blue and grey geometric pattern area rug. Machine washable. Adds warmth to any room.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '5\'x7\'',
    color: 'Blue/Grey',
    donorType: 'Family Donor',
    postedDate: '2025-03-14',
    expiryDate: '2025-04-14',
    tags: ['apartment', 'student-friendly'],
    views: 88,
    requests: 7,
    images: ['rug1'],
  },
  {
    id: '11',
    name: 'Microwave Oven',
    category: 'Appliances',
    condition: 'Good',
    description: 'Countertop microwave 700W. All functions work perfectly. 1.1 cubic feet capacity.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '17"W x 13"D x 10"H',
    color: 'Black',
    donorType: 'Community Member',
    postedDate: '2025-03-19',
    expiryDate: '2025-04-19',
    tags: ['dorm-ready', 'compact', 'free', 'student-friendly'],
    views: 189,
    requests: 14,
    images: ['microwave1'],
  },
  {
    id: '12',
    name: 'Dining Table',
    category: 'Tables',
    condition: 'Good',
    description: 'Wooden 4-person dining table. Light oak finish. Seats four comfortably. Minor surface scratches.',
    location: LOCATIONS[1],
    availability: 'Available',
    pickupType: 'Scheduled',
    dimensions: '48"W x 30"D x 30"H',
    color: 'Oak',
    donorType: 'Family Donor',
    postedDate: '2025-03-11',
    expiryDate: '2025-04-11',
    tags: ['apartment', 'lightly-used'],
    views: 156,
    requests: 9,
    images: ['table1', 'table2'],
  },
  {
    id: '13',
    name: 'Couch - Grey Sectional',
    category: 'Couches',
    condition: 'Fair',
    description: 'Grey L-shaped sectional couch. Left chaise included. Some wear on cushions but fully functional.',
    location: LOCATIONS[1],
    availability: 'Available',
    pickupType: 'Curbside',
    dimensions: '110"W x 85"D x 33"H',
    color: 'Grey',
    donorType: 'Family Donor',
    postedDate: '2025-03-07',
    expiryDate: '2025-04-07',
    tags: ['apartment', 'urgent-pickup'],
    views: 220,
    requests: 11,
    images: ['sectional1'],
  },
  {
    id: '14',
    name: 'Dresser with Mirror',
    category: 'Storage',
    condition: 'Good',
    description: '6-drawer dresser with attached mirror. White finish. Dovetail drawer construction.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '48"W x 19"D x 66"H with mirror',
    color: 'White',
    donorType: 'Family Donor',
    postedDate: '2025-03-16',
    expiryDate: '2025-04-16',
    tags: ['apartment', 'lightly-used'],
    views: 134,
    requests: 8,
    images: ['dresser1'],
  },
  {
    id: '15',
    name: 'Kids\' Toy Set',
    category: 'Toys',
    condition: 'Good',
    description: 'Large box of children\'s toys including blocks, puzzles, stuffed animals. Ages 2-8.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: 'Box: 24"x18"x16"',
    color: 'Mixed',
    donorType: 'Family Donor',
    postedDate: '2025-03-21',
    expiryDate: '2025-04-21',
    tags: ['free', 'compact'],
    views: 43,
    requests: 2,
    images: ['toys1'],
  },
  {
    id: '16',
    name: 'Wall Mirror - Oval',
    category: 'Mirrors',
    condition: 'Like New',
    description: 'Gold-framed oval wall mirror. 24"x36". Great for bedroom or entryway. Comes with mounting hardware.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '24"W x 36"H',
    color: 'Gold Frame',
    donorType: 'Student Donor',
    postedDate: '2025-03-24',
    expiryDate: '2025-04-24',
    tags: ['apartment', 'compact', 'lightly-used'],
    views: 71,
    requests: 5,
    images: ['mirror1'],
  },
  {
    id: '17',
    name: 'Coffee Table - Modern',
    category: 'Tables',
    condition: 'Good',
    description: 'White and chrome modern coffee table with storage shelf below. Glass top surface.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '47"W x 24"D x 18"H',
    color: 'White/Chrome',
    donorType: 'Community Member',
    postedDate: '2025-03-13',
    expiryDate: '2025-04-13',
    tags: ['apartment', 'student-friendly'],
    views: 112,
    requests: 6,
    images: ['coffeetable1'],
  },
  {
    id: '18',
    name: 'Single Bed Frame',
    category: 'Bed Frames',
    condition: 'Good',
    description: 'Metal twin/single bed frame. No headboard. Universal design fits standard twin mattresses.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '39"W x 75"L x 14"H',
    color: 'Black Metal',
    donorType: 'Student Donor',
    postedDate: '2025-03-17',
    expiryDate: '2025-04-17',
    tags: ['dorm-ready', 'compact', 'student-friendly'],
    views: 165,
    requests: 13,
    images: ['bedframe2'],
  },
  {
    id: '19',
    name: 'Accent Chair',
    category: 'Chairs',
    condition: 'Like New',
    description: 'Velvet teal accent chair with gold metal legs. Never used. Perfect statement piece.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '28"W x 30"D x 33"H',
    color: 'Teal Velvet',
    donorType: 'Faculty',
    postedDate: '2025-03-26',
    expiryDate: '2025-04-26',
    tags: ['apartment', 'lightly-used', 'student-friendly'],
    views: 198,
    requests: 17,
    images: ['chair2'],
  },
  {
    id: '20',
    name: 'Bookshelf - 3-Tier',
    category: 'Bookshelves',
    condition: 'Fair',
    description: 'Simple 3-tier wooden bookshelf. Light brown. Some assembly required. Great for dorms.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '24"W x 10"D x 36"H',
    color: 'Light Brown',
    donorType: 'Student Donor',
    postedDate: '2025-03-09',
    expiryDate: '2025-04-09',
    tags: ['dorm-ready', 'compact', 'student-friendly', 'free'],
    views: 76,
    requests: 5,
    images: ['bookshelf2'],
  },
  {
    id: '21',
    name: 'Kitchen Pots and Pans Set',
    category: 'Kitchen Items',
    condition: 'Good',
    description: '10-piece cookware set. Non-stick coating. Includes pots, pans, and lids. Good condition.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: 'Various sizes',
    color: 'Black',
    donorType: 'Family Donor',
    postedDate: '2025-03-22',
    expiryDate: '2025-04-22',
    tags: ['apartment', 'student-friendly', 'compact'],
    views: 143,
    requests: 11,
    images: ['pots1'],
  },
  {
    id: '22',
    name: 'Desk Lamp - LED',
    category: 'Lamps',
    condition: 'Like New',
    description: 'LED desk lamp with 3 brightness levels and USB charging port. Eye-care design.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '6"W x 18"H',
    color: 'White',
    donorType: 'Student Donor',
    postedDate: '2025-03-27',
    expiryDate: '2025-04-27',
    tags: ['dorm-ready', 'compact', 'student-friendly', 'free'],
    views: 203,
    requests: 18,
    images: ['desklamp1'],
  },
  {
    id: '23',
    name: '55" Vizio Smart TV',
    category: 'Televisions',
    condition: 'Good',
    description: 'Vizio 55-inch 4K smart TV. Apps working including Netflix and YouTube. Remote included.',
    location: LOCATIONS[1],
    availability: 'Available',
    pickupType: 'Scheduled',
    dimensions: '48"W x 28"H x 3"D',
    color: 'Black',
    donorType: 'Community Member',
    postedDate: '2025-03-15',
    expiryDate: '2025-04-15',
    tags: ['apartment', 'lightly-used'],
    views: 489,
    requests: 34,
    images: ['tv2'],
  },
  {
    id: '24',
    name: 'Futon Sofa Bed',
    category: 'Sofas',
    condition: 'Good',
    description: 'Black metal futon that converts from sofa to bed. Great for studio apartments.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '75"W x 32"D x 33"H (sofa)',
    color: 'Black',
    donorType: 'Student Donor',
    postedDate: '2025-03-18',
    expiryDate: '2025-04-18',
    tags: ['apartment', 'student-friendly', 'dorm-ready'],
    views: 267,
    requests: 21,
    images: ['futon1'],
  },
  {
    id: '25',
    name: 'Storage Ottoman',
    category: 'Storage',
    condition: 'Like New',
    description: 'Grey fabric storage ottoman with tray top. Opens for storage inside. Multipurpose.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '36"W x 18"D x 18"H',
    color: 'Grey',
    donorType: 'Faculty',
    postedDate: '2025-03-28',
    expiryDate: '2025-04-28',
    tags: ['compact', 'apartment', 'dorm-ready'],
    views: 87,
    requests: 6,
    images: ['ottoman1'],
  },
  {
    id: '26',
    name: 'Plastic Storage Bins (Set of 6)',
    category: 'Storage',
    condition: 'Good',
    description: 'Clear plastic storage bins with lids. Various sizes. Great for organizing dorm or apartment.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: 'Various: S/M/L',
    color: 'Clear',
    donorType: 'Student Donor',
    postedDate: '2025-03-21',
    expiryDate: '2025-04-21',
    tags: ['dorm-ready', 'compact', 'student-friendly', 'free'],
    views: 56,
    requests: 4,
    images: ['bins1'],
  },
  {
    id: '27',
    name: 'Folding Dining Chairs (Set of 4)',
    category: 'Chairs',
    condition: 'Good',
    description: 'Metal folding chairs with padded seats. Easy to store when not in use. Set of 4.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '17"W x 18"D x 33"H each',
    color: 'Black',
    donorType: 'Community Member',
    postedDate: '2025-03-14',
    expiryDate: '2025-04-14',
    tags: ['apartment', 'compact', 'student-friendly'],
    views: 132,
    requests: 8,
    images: ['chairs1'],
  },
  {
    id: '28',
    name: 'Twin Mattress',
    category: 'Mattresses',
    condition: 'Good',
    description: 'Clean twin mattress. No odors. Good support. Sanitized. Ready for immediate use.',
    location: LOCATIONS[1],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '39"W x 75"L x 8"H',
    color: 'White/Blue',
    donorType: 'Student Donor',
    postedDate: '2025-03-10',
    expiryDate: '2025-04-10',
    tags: ['dorm-ready', 'student-friendly'],
    views: 231,
    requests: 16,
    images: ['mattress2'],
  },
  {
    id: '29',
    name: 'Rocking Chair',
    category: 'Chairs',
    condition: 'Good',
    description: 'Classic wooden rocking chair. Great for relaxing. Solid oak construction.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '24"W x 32"D x 40"H',
    color: 'Natural Oak',
    donorType: 'Family Donor',
    postedDate: '2025-03-06',
    expiryDate: '2025-04-06',
    tags: ['apartment', 'lightly-used'],
    views: 63,
    requests: 3,
    images: ['rocker1'],
  },
  {
    id: '30',
    name: 'Blender',
    category: 'Appliances',
    condition: 'Like New',
    description: 'Ninja blender with 3 speeds. All attachments included. Great for smoothies.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '7"W x 7"D x 15"H',
    color: 'Black',
    donorType: 'Student Donor',
    postedDate: '2025-03-25',
    expiryDate: '2025-04-25',
    tags: ['compact', 'dorm-ready', 'free', 'student-friendly'],
    views: 178,
    requests: 12,
    images: ['blender1'],
  },
  {
    id: '31',
    name: 'Couch - Blue Loveseat',
    category: 'Couches',
    condition: 'Good',
    description: 'Navy blue fabric loveseat. Clean and comfortable. 2-seater. Perfect for small spaces.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '56"W x 33"D x 35"H',
    color: 'Navy Blue',
    donorType: 'Community Member',
    postedDate: '2025-03-19',
    expiryDate: '2025-04-19',
    tags: ['apartment', 'compact', 'student-friendly'],
    views: 145,
    requests: 10,
    images: ['loveseat1'],
  },
  {
    id: '32',
    name: 'Toaster Oven',
    category: 'Appliances',
    condition: 'Good',
    description: '6-slice toaster oven with convection. Includes rack and baking pan. Works perfectly.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '16"W x 12"D x 10"H',
    color: 'Silver',
    donorType: 'Family Donor',
    postedDate: '2025-03-20',
    expiryDate: '2025-04-20',
    tags: ['dorm-ready', 'compact', 'student-friendly', 'free'],
    views: 201,
    requests: 15,
    images: ['toasteroven1'],
  },
  {
    id: '33',
    name: 'Nightstand',
    category: 'Tables',
    condition: 'Good',
    description: 'White nightstand with drawer and bottom shelf. Clean and functional.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '22"W x 16"D x 26"H',
    color: 'White',
    donorType: 'Student Donor',
    postedDate: '2025-03-16',
    expiryDate: '2025-04-16',
    tags: ['dorm-ready', 'compact', 'student-friendly'],
    views: 87,
    requests: 7,
    images: ['nightstand1'],
  },
  {
    id: '34',
    name: 'Computer Desk - L-Shape',
    category: 'Study Desks',
    condition: 'Good',
    description: 'Large L-shaped computer desk. Ample workspace for dual monitors. Some assembly required.',
    location: LOCATIONS[1],
    availability: 'Available',
    pickupType: 'Scheduled',
    dimensions: '60"W x 24"D main, 40"W x 20"D return',
    color: 'Black',
    donorType: 'Faculty',
    postedDate: '2025-03-13',
    expiryDate: '2025-04-13',
    tags: ['apartment', 'student-friendly'],
    views: 256,
    requests: 19,
    images: ['ldesk1'],
  },
  {
    id: '35',
    name: 'Exercise Bike',
    category: 'Miscellaneous',
    condition: 'Good',
    description: 'Stationary exercise bike with adjustable resistance. Display shows speed and calories.',
    location: LOCATIONS[1],
    availability: 'Available',
    pickupType: 'Scheduled',
    dimensions: '40"L x 22"W x 46"H',
    color: 'Black/White',
    donorType: 'Community Member',
    postedDate: '2025-03-11',
    expiryDate: '2025-04-11',
    tags: ['apartment', 'lightly-used'],
    views: 167,
    requests: 8,
    images: ['bike1'],
  },
  {
    id: '36',
    name: 'Bed - King with Frame',
    category: 'Beds',
    condition: 'Good',
    description: 'King size bed with upholstered headboard and frame. Clean and ready to use.',
    location: LOCATIONS[1],
    availability: 'Available',
    pickupType: 'Curbside',
    dimensions: '76"W x 80"L x 54"H',
    color: 'Grey',
    donorType: 'Family Donor',
    postedDate: '2025-03-08',
    expiryDate: '2025-04-08',
    tags: ['apartment', 'lightly-used'],
    views: 312,
    requests: 24,
    images: ['kingbed1'],
  },
  {
    id: '37',
    name: 'Standing Desk',
    category: 'Study Desks',
    condition: 'Like New',
    description: 'Electric height-adjustable standing desk. 3 memory presets. Excellent condition.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '55"W x 28"D',
    color: 'White',
    donorType: 'Corporate Donor',
    postedDate: '2025-03-29',
    expiryDate: '2025-04-29',
    tags: ['apartment', 'student-friendly', 'lightly-used'],
    views: 445,
    requests: 31,
    images: ['standingdesk1'],
  },
  {
    id: '38',
    name: 'Coffee Maker',
    category: 'Appliances',
    condition: 'Good',
    description: '12-cup drip coffee maker. Programmable timer. Includes carafe and filter basket.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '9"W x 8"D x 13"H',
    color: 'Black',
    donorType: 'Student Donor',
    postedDate: '2025-03-24',
    expiryDate: '2025-04-24',
    tags: ['dorm-ready', 'compact', 'free', 'student-friendly'],
    views: 234,
    requests: 17,
    images: ['coffeemaker1'],
  },
  {
    id: '39',
    name: 'Carpet 8x10',
    category: 'Rugs',
    condition: 'Good',
    description: 'Traditional pattern carpet in beige and cream. Great for living room.',
    location: LOCATIONS[1],
    availability: 'Available',
    pickupType: 'Curbside',
    dimensions: '8\'x10\'',
    color: 'Beige/Cream',
    donorType: 'Family Donor',
    postedDate: '2025-03-12',
    expiryDate: '2025-04-12',
    tags: ['apartment', 'lightly-used'],
    views: 78,
    requests: 4,
    images: ['carpet1'],
  },
  {
    id: '40',
    name: 'Dish Set (Service for 4)',
    category: 'Kitchen Items',
    condition: 'Good',
    description: 'Complete dinnerware set for 4. Includes plates, bowls, and mugs. White ceramic.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: 'Standard plates 10"',
    color: 'White',
    donorType: 'Community Member',
    postedDate: '2025-03-21',
    expiryDate: '2025-04-21',
    tags: ['apartment', 'student-friendly', 'compact', 'free'],
    views: 123,
    requests: 9,
    images: ['dishes1'],
  },
  {
    id: '41',
    name: 'Bar Stools (Set of 2)',
    category: 'Chairs',
    condition: 'Like New',
    description: 'Counter-height bar stools with footrest. Swivel seat. Black metal base. Set of 2.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '15"W x 15"D x 29"H seat',
    color: 'Black/Grey',
    donorType: 'Faculty',
    postedDate: '2025-03-28',
    expiryDate: '2025-04-28',
    tags: ['apartment', 'student-friendly', 'lightly-used'],
    views: 167,
    requests: 13,
    images: ['barstool1'],
  },
  {
    id: '42',
    name: 'Outdoor Folding Table',
    category: 'Tables',
    condition: 'Good',
    description: '6-foot folding table. Plastic top. Great for outdoor use or extra table space.',
    location: LOCATIONS[2],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '72"W x 30"D x 29"H',
    color: 'White',
    donorType: 'Community Member',
    postedDate: '2025-03-17',
    expiryDate: '2025-04-17',
    tags: ['compact', 'student-friendly', 'free'],
    views: 89,
    requests: 5,
    images: ['foldingtable1'],
  },
  {
    id: '43',
    name: 'Vacuum Cleaner',
    category: 'Appliances',
    condition: 'Good',
    description: 'Upright vacuum cleaner. Bagless with HEPA filter. Works well on carpet and hardwood.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '12"W x 12"D x 45"H',
    color: 'Red/Grey',
    donorType: 'Family Donor',
    postedDate: '2025-03-18',
    expiryDate: '2025-04-18',
    tags: ['apartment', 'student-friendly'],
    views: 198,
    requests: 14,
    images: ['vacuum1'],
  },
  {
    id: '44',
    name: 'Wall Shelves Set',
    category: 'Storage',
    condition: 'Like New',
    description: 'Set of 3 floating wall shelves. White. Hardware included. Perfect for dorm or apartment.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '24"W x 6"D each',
    color: 'White',
    donorType: 'Student Donor',
    postedDate: '2025-03-26',
    expiryDate: '2025-04-26',
    tags: ['dorm-ready', 'compact', 'student-friendly', 'lightly-used'],
    views: 112,
    requests: 8,
    images: ['wallshelves1'],
  },
  {
    id: '45',
    name: 'Rice Cooker',
    category: 'Appliances',
    condition: 'Like New',
    description: '6-cup rice cooker and food steamer. Aroma brand. Non-stick pot. Quick cook setting.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '8"W x 8"D x 8"H',
    color: 'White',
    donorType: 'Student Donor',
    postedDate: '2025-03-27',
    expiryDate: '2025-04-27',
    tags: ['dorm-ready', 'compact', 'student-friendly', 'free'],
    views: 245,
    requests: 19,
    images: ['ricecooker1'],
  },
  {
    id: '46',
    name: 'Loveseat Recliner',
    category: 'Sofas',
    condition: 'Good',
    description: 'Brown microfiber reclining loveseat. Both seats recline. Perfect for apartments.',
    location: LOCATIONS[1],
    availability: 'Available',
    pickupType: 'Curbside',
    dimensions: '60"W x 38"D x 40"H',
    color: 'Brown',
    donorType: 'Family Donor',
    postedDate: '2025-03-09',
    expiryDate: '2025-04-09',
    tags: ['apartment', 'lightly-used'],
    views: 187,
    requests: 13,
    images: ['recliner1'],
  },
  {
    id: '47',
    name: 'Toaster - 4 Slice',
    category: 'Appliances',
    condition: 'Good',
    description: '4-slice toaster with bagel and cancel functions. Chrome finish. Works great.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '12"W x 6"D x 8"H',
    color: 'Silver',
    donorType: 'Community Member',
    postedDate: '2025-03-23',
    expiryDate: '2025-04-23',
    tags: ['dorm-ready', 'compact', 'free'],
    views: 145,
    requests: 10,
    images: ['toaster1'],
  },
  {
    id: '48',
    name: 'Metal Shelving Unit',
    category: 'Storage',
    condition: 'Good',
    description: '5-tier metal wire shelving unit. Great for garage, basement, or utility storage.',
    location: LOCATIONS[1],
    availability: 'Available',
    pickupType: 'Scheduled',
    dimensions: '36"W x 14"D x 72"H',
    color: 'Chrome',
    donorType: 'Corporate Donor',
    postedDate: '2025-03-14',
    expiryDate: '2025-04-14',
    tags: ['apartment', 'student-friendly'],
    views: 98,
    requests: 6,
    images: ['shelving1'],
  },
  {
    id: '49',
    name: 'Sofa - Beige 2-Seater',
    category: 'Sofas',
    condition: 'Fair',
    description: 'Beige fabric 2-seater sofa. Functional but has some visible wear. Great for budget setup.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '65"W x 34"D x 33"H',
    color: 'Beige',
    donorType: 'Community Member',
    postedDate: '2025-03-07',
    expiryDate: '2025-04-07',
    tags: ['apartment', 'urgent-pickup', 'student-friendly'],
    views: 134,
    requests: 7,
    images: ['sofa2'],
  },
  {
    id: '50',
    name: 'Laundry Hamper',
    category: 'Miscellaneous',
    condition: 'Like New',
    description: 'Large canvas laundry hamper on wheels. Removable liner. Perfect for dorm.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '16"W x 12"D x 24"H',
    color: 'Grey',
    donorType: 'Student Donor',
    postedDate: '2025-03-29',
    expiryDate: '2025-04-29',
    tags: ['dorm-ready', 'compact', 'student-friendly', 'free'],
    views: 67,
    requests: 5,
    images: ['hamper1'],
  },
  {
    id: '51',
    name: 'Towel Set (6-piece)',
    category: 'Miscellaneous',
    condition: 'Good',
    description: '6-piece towel set: 2 bath, 2 hand, 2 washcloths. Soft cotton. White.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: 'Standard size',
    color: 'White',
    donorType: 'Family Donor',
    postedDate: '2025-03-22',
    expiryDate: '2025-04-22',
    tags: ['dorm-ready', 'compact', 'free', 'student-friendly'],
    views: 45,
    requests: 4,
    images: ['towels1'],
  },
  {
    id: '52',
    name: 'Ironing Board',
    category: 'Miscellaneous',
    condition: 'Good',
    description: 'Full-size ironing board with adjustable height. Comes with cover. Folds flat for storage.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '54"L x 15"W',
    color: 'Grey/Blue',
    donorType: 'Community Member',
    postedDate: '2025-03-20',
    expiryDate: '2025-04-20',
    tags: ['apartment', 'student-friendly', 'compact'],
    views: 56,
    requests: 3,
    images: ['ironingboard1'],
  },
  {
    id: '53',
    name: 'Floor Mirror - Full Length',
    category: 'Mirrors',
    condition: 'Good',
    description: 'Full-length leaning floor mirror. Black frame. 65"x22". Great for bedroom.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '22"W x 65"H',
    color: 'Black Frame',
    donorType: 'Student Donor',
    postedDate: '2025-03-16',
    expiryDate: '2025-04-16',
    tags: ['dorm-ready', 'compact', 'apartment'],
    views: 178,
    requests: 13,
    images: ['floormirror1'],
  },
  {
    id: '54',
    name: 'Wicker Storage Basket Set',
    category: 'Storage',
    condition: 'Like New',
    description: 'Set of 3 wicker baskets in graduated sizes. Natural finish. Great for organizing.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: 'S:8" M:10" L:13"',
    color: 'Natural Wicker',
    donorType: 'Faculty',
    postedDate: '2025-03-27',
    expiryDate: '2025-04-27',
    tags: ['compact', 'apartment', 'dorm-ready'],
    views: 89,
    requests: 7,
    images: ['baskets1'],
  },
  {
    id: '55',
    name: 'Air Purifier',
    category: 'Appliances',
    condition: 'Good',
    description: 'HEPA air purifier, covers 300 sq ft. Quiet operation. New filter included.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '10"W x 6"D x 17"H',
    color: 'White',
    donorType: 'Corporate Donor',
    postedDate: '2025-03-25',
    expiryDate: '2025-04-25',
    tags: ['apartment', 'student-friendly', 'compact'],
    views: 212,
    requests: 16,
    images: ['airpurifier1'],
  },
  {
    id: '56',
    name: 'Computer Monitor - 24"',
    category: 'Miscellaneous',
    condition: 'Like New',
    description: 'Dell 24-inch IPS monitor. 1080p resolution. HDMI and VGA ports. No dead pixels.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '22"W x 13"H',
    color: 'Black',
    donorType: 'Faculty',
    postedDate: '2025-03-28',
    expiryDate: '2025-04-28',
    tags: ['student-friendly', 'apartment', 'lightly-used'],
    views: 345,
    requests: 27,
    images: ['monitor1'],
  },
  {
    id: '57',
    name: 'Dining Chair Set (4)',
    category: 'Chairs',
    condition: 'Good',
    description: 'Set of 4 padded dining chairs. Dark grey fabric with chrome legs. Comfortable.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '18"W x 22"D x 36"H',
    color: 'Grey/Chrome',
    donorType: 'Family Donor',
    postedDate: '2025-03-13',
    expiryDate: '2025-04-13',
    tags: ['apartment', 'lightly-used'],
    views: 143,
    requests: 9,
    images: ['diningchairs1'],
  },
  {
    id: '58',
    name: 'Printer - HP LaserJet',
    category: 'Miscellaneous',
    condition: 'Good',
    description: 'HP LaserJet Pro printer. Wireless capable. Half-full toner cartridge included.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '14"W x 10"D x 8"H',
    color: 'Black',
    donorType: 'Faculty',
    postedDate: '2025-03-19',
    expiryDate: '2025-04-19',
    tags: ['student-friendly', 'dorm-ready', 'apartment'],
    views: 289,
    requests: 22,
    images: ['printer1'],
  },
  {
    id: '59',
    name: 'Throw Blankets (Set of 2)',
    category: 'Miscellaneous',
    condition: 'Like New',
    description: 'Soft fleece throw blankets. 50"x60". Teal and grey. Perfect for cozy nights.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '50"x60" each',
    color: 'Teal/Grey',
    donorType: 'Community Member',
    postedDate: '2025-03-25',
    expiryDate: '2025-04-25',
    tags: ['dorm-ready', 'compact', 'student-friendly', 'free'],
    views: 78,
    requests: 6,
    images: ['blankets1'],
  },
  {
    id: '60',
    name: 'Changing Table',
    category: 'Tables',
    condition: 'Good',
    description: 'Baby changing table with storage drawers. White wood. Great condition.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '33"W x 18"D x 38"H',
    color: 'White',
    donorType: 'Family Donor',
    postedDate: '2025-03-15',
    expiryDate: '2025-04-15',
    tags: ['free'],
    views: 67,
    requests: 4,
    images: ['changingtable1'],
  },
  {
    id: '61',
    name: 'Bean Bag Chair',
    category: 'Chairs',
    condition: 'Good',
    description: 'Large bean bag chair. Red faux leather. Fully filled. Great for gaming or relaxing.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '38" diameter',
    color: 'Red',
    donorType: 'Student Donor',
    postedDate: '2025-03-22',
    expiryDate: '2025-04-22',
    tags: ['dorm-ready', 'student-friendly', 'compact'],
    views: 156,
    requests: 12,
    images: ['beanbag1'],
  },
  {
    id: '62',
    name: 'Spice Rack',
    category: 'Kitchen Items',
    condition: 'Like New',
    description: 'Rotating spice rack holds 20 jars. Chrome finish. Countertop carousel style.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '8"W x 8"D x 12"H',
    color: 'Chrome',
    donorType: 'Community Member',
    postedDate: '2025-03-26',
    expiryDate: '2025-04-26',
    tags: ['compact', 'dorm-ready', 'free', 'student-friendly'],
    views: 54,
    requests: 3,
    images: ['spicerack1'],
  },
  {
    id: '63',
    name: 'Bathroom Shelving',
    category: 'Storage',
    condition: 'Good',
    description: 'Over-toilet bathroom shelving unit. White. 3 shelves. Easy to install.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '26"W x 8"D x 65"H',
    color: 'White',
    donorType: 'Student Donor',
    postedDate: '2025-03-18',
    expiryDate: '2025-04-18',
    tags: ['dorm-ready', 'compact', 'student-friendly'],
    views: 89,
    requests: 6,
    images: ['bathshelving1'],
  },
  {
    id: '64',
    name: 'Ceiling Fan',
    category: 'Miscellaneous',
    condition: 'Good',
    description: 'Hunter 52" ceiling fan with light kit. Remote control included. Brushed nickel finish.',
    location: LOCATIONS[1],
    availability: 'Available',
    pickupType: 'Scheduled',
    dimensions: '52" blade span',
    color: 'Brushed Nickel',
    donorType: 'Family Donor',
    postedDate: '2025-03-10',
    expiryDate: '2025-04-10',
    tags: ['apartment'],
    views: 123,
    requests: 7,
    images: ['fan1'],
  },
  {
    id: '65',
    name: 'Compact Refrigerator',
    category: 'Appliances',
    condition: 'Good',
    description: '3.2 cubic foot compact fridge. Black. Works perfectly. Has small freezer compartment.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '18"W x 20"D x 34"H',
    color: 'Black',
    donorType: 'Student Donor',
    postedDate: '2025-03-17',
    expiryDate: '2025-04-17',
    tags: ['dorm-ready', 'compact', 'student-friendly', 'free'],
    views: 412,
    requests: 32,
    images: ['minifridge1'],
  },
  {
    id: '66',
    name: 'Plant Stand',
    category: 'Miscellaneous',
    condition: 'Like New',
    description: 'Tiered wooden plant stand. 3 levels. Natural finish. Holds 6+ plants.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '22"W x 12"D x 36"H',
    color: 'Natural Wood',
    donorType: 'Faculty',
    postedDate: '2025-03-27',
    expiryDate: '2025-04-27',
    tags: ['apartment', 'compact', 'lightly-used'],
    views: 87,
    requests: 6,
    images: ['plantstand1'],
  },
  {
    id: '67',
    name: 'Keyboard and Mouse Set',
    category: 'Miscellaneous',
    condition: 'Good',
    description: 'Wireless keyboard and mouse combo. Logitech. USB receiver. Batteries included.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: 'Standard',
    color: 'Black',
    donorType: 'Faculty',
    postedDate: '2025-03-24',
    expiryDate: '2025-04-24',
    tags: ['student-friendly', 'compact', 'free', 'dorm-ready'],
    views: 234,
    requests: 18,
    images: ['keyboard1'],
  },
  {
    id: '68',
    name: 'Curtain Set',
    category: 'Miscellaneous',
    condition: 'Good',
    description: 'Set of 2 blackout curtain panels. 84" length. Grey. Includes curtain rod.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '52"W x 84"L each panel',
    color: 'Grey',
    donorType: 'Community Member',
    postedDate: '2025-03-21',
    expiryDate: '2025-04-21',
    tags: ['apartment', 'student-friendly', 'dorm-ready'],
    views: 112,
    requests: 8,
    images: ['curtains1'],
  },
  {
    id: '69',
    name: 'Shoe Rack',
    category: 'Storage',
    condition: 'Like New',
    description: '4-tier shoe rack. Metal and plastic. Holds 20+ pairs. Easy assembly.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '20"W x 12"D x 53"H',
    color: 'Black',
    donorType: 'Student Donor',
    postedDate: '2025-03-29',
    expiryDate: '2025-04-29',
    tags: ['compact', 'dorm-ready', 'student-friendly', 'free'],
    views: 95,
    requests: 7,
    images: ['shoerack1'],
  },
  {
    id: '70',
    name: 'Twin XL Mattress',
    category: 'Mattresses',
    condition: 'Good',
    description: 'Twin XL mattress. Perfect for dorm beds. No stains. Sanitized. Firm support.',
    location: LOCATIONS[1],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '39"W x 80"L x 9"H',
    color: 'White',
    donorType: 'Student Donor',
    postedDate: '2025-03-13',
    expiryDate: '2025-04-13',
    tags: ['dorm-ready', 'student-friendly', 'urgent-pickup'],
    views: 356,
    requests: 28,
    images: ['mattress3'],
  },
  {
    id: '71',
    name: 'Mini Fridge with Freezer',
    category: 'Appliances',
    condition: 'Good',
    description: '4.4 cubic foot fridge with separate freezer door. White. Perfect for dorm room.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '20"W x 22"D x 43"H',
    color: 'White',
    donorType: 'Family Donor',
    postedDate: '2025-03-12',
    expiryDate: '2025-04-12',
    tags: ['dorm-ready', 'compact', 'student-friendly'],
    views: 389,
    requests: 29,
    images: ['minifridge2'],
  },
  {
    id: '72',
    name: 'Folding Table - Card Table',
    category: 'Tables',
    condition: 'Good',
    description: 'Classic folding card table. 34"x34". Green felt top. Sturdy metal legs.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '34"W x 34"D x 29"H',
    color: 'Green/Silver',
    donorType: 'Community Member',
    postedDate: '2025-03-19',
    expiryDate: '2025-04-19',
    tags: ['compact', 'student-friendly', 'free'],
    views: 67,
    requests: 4,
    images: ['cardtable1'],
  },
  {
    id: '73',
    name: 'Outdoor Lawn Chairs (Pair)',
    category: 'Chairs',
    condition: 'Good',
    description: 'Pair of folding outdoor lawn chairs. Blue and white stripe fabric. Foldable for storage.',
    location: LOCATIONS[2],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '24"W x 32"D x 36"H',
    color: 'Blue/White',
    donorType: 'Family Donor',
    postedDate: '2025-03-15',
    expiryDate: '2025-04-15',
    tags: ['compact', 'student-friendly', 'free'],
    views: 78,
    requests: 5,
    images: ['lawnchairs1'],
  },
  {
    id: '74',
    name: 'Filing Cabinet',
    category: 'Storage',
    condition: 'Good',
    description: '2-drawer metal filing cabinet. Black. Letter size. Comes with key.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '15"W x 19"D x 29"H',
    color: 'Black',
    donorType: 'Faculty',
    postedDate: '2025-03-16',
    expiryDate: '2025-04-16',
    tags: ['compact', 'student-friendly', 'apartment'],
    views: 112,
    requests: 7,
    images: ['filecabinet1'],
  },
  {
    id: '75',
    name: 'Reading Lamp',
    category: 'Lamps',
    condition: 'Like New',
    description: 'Adjustable reading lamp with clamp. LED bulb included. Perfect for beds or desks.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '4"W x 20"H arm',
    color: 'Black',
    donorType: 'Student Donor',
    postedDate: '2025-03-27',
    expiryDate: '2025-04-27',
    tags: ['dorm-ready', 'compact', 'student-friendly', 'free'],
    views: 145,
    requests: 11,
    images: ['readinglamp1'],
  },
  {
    id: '76',
    name: 'Couch Sectional - 3 Piece',
    category: 'Couches',
    condition: 'Good',
    description: 'Large modular sectional couch. Grey microfiber. 3 connectable pieces for flexible arrangement.',
    location: LOCATIONS[1],
    availability: 'Available',
    pickupType: 'Curbside',
    dimensions: '120"W x 98"D x 33"H',
    color: 'Grey',
    donorType: 'Family Donor',
    postedDate: '2025-03-08',
    expiryDate: '2025-04-08',
    tags: ['apartment', 'lightly-used', 'urgent-pickup'],
    views: 267,
    requests: 18,
    images: ['sectional2'],
  },
  {
    id: '77',
    name: 'Electric Kettle',
    category: 'Appliances',
    condition: 'Like New',
    description: '1.7L electric kettle with temperature control. Stainless steel. Auto-shutoff.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '7"W x 9"H',
    color: 'Stainless',
    donorType: 'Student Donor',
    postedDate: '2025-03-28',
    expiryDate: '2025-04-28',
    tags: ['dorm-ready', 'compact', 'free', 'student-friendly'],
    views: 198,
    requests: 15,
    images: ['kettle1'],
  },
  {
    id: '78',
    name: 'Bed Side Table (Pair)',
    category: 'Tables',
    condition: 'Good',
    description: 'Matching pair of bedside tables. Espresso finish. One drawer each.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '18"W x 16"D x 24"H each',
    color: 'Espresso',
    donorType: 'Family Donor',
    postedDate: '2025-03-11',
    expiryDate: '2025-04-11',
    tags: ['apartment', 'lightly-used'],
    views: 123,
    requests: 8,
    images: ['sidetables1'],
  },
  {
    id: '79',
    name: 'Folding Bike',
    category: 'Miscellaneous',
    condition: 'Good',
    description: 'Dahon folding bicycle. 20" wheels. 7 speeds. Folds compact for easy storage. Needs minor tune-up.',
    location: LOCATIONS[2],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '42"L x 25"H folded',
    color: 'Blue',
    donorType: 'Community Member',
    postedDate: '2025-03-14',
    expiryDate: '2025-04-14',
    tags: ['student-friendly', 'compact'],
    views: 289,
    requests: 21,
    images: ['bike2'],
  },
  {
    id: '80',
    name: 'Throw Pillows (Set of 4)',
    category: 'Miscellaneous',
    condition: 'Like New',
    description: 'Decorative throw pillows. Assorted sizes. Teal, grey, and mustard yellow colors.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '18"x18" and 12"x20"',
    color: 'Teal/Grey/Yellow',
    donorType: 'Community Member',
    postedDate: '2025-03-24',
    expiryDate: '2025-04-24',
    tags: ['compact', 'dorm-ready', 'free', 'student-friendly'],
    views: 56,
    requests: 4,
    images: ['pillows1'],
  },
  {
    id: '81',
    name: 'Desk - Bamboo',
    category: 'Study Desks',
    condition: 'Like New',
    description: 'Solid bamboo writing desk. Natural finish. Clean lines. Perfect for small spaces.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '47"W x 23"D x 30"H',
    color: 'Natural Bamboo',
    donorType: 'Faculty',
    postedDate: '2025-03-30',
    expiryDate: '2025-04-30',
    tags: ['student-friendly', 'compact', 'apartment'],
    views: 234,
    requests: 17,
    images: ['bamboodsk1'],
  },
  {
    id: '82',
    name: 'Book Collection (25+ books)',
    category: 'Miscellaneous',
    condition: 'Good',
    description: 'Mixed collection of 25+ books. Fiction, non-fiction, and textbooks. Various subjects.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: 'Box: 18"x12"x10"',
    color: 'Various',
    donorType: 'Family Donor',
    postedDate: '2025-03-20',
    expiryDate: '2025-04-20',
    tags: ['student-friendly', 'compact', 'free', 'dorm-ready'],
    views: 89,
    requests: 7,
    images: ['books1'],
  },
  {
    id: '83',
    name: 'Stepladder - 2 Step',
    category: 'Miscellaneous',
    condition: 'Good',
    description: 'Small 2-step folding ladder. Aluminum. 200 lb capacity. Great for reaching high shelves.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '16"W x 22"D x 24"H',
    color: 'Silver',
    donorType: 'Community Member',
    postedDate: '2025-03-18',
    expiryDate: '2025-04-18',
    tags: ['compact', 'apartment', 'student-friendly'],
    views: 67,
    requests: 4,
    images: ['ladder1'],
  },
  {
    id: '84',
    name: 'Folding Room Divider',
    category: 'Miscellaneous',
    condition: 'Good',
    description: '4-panel room divider screen. Bamboo. 6 feet tall. Great for studio apartments.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '72"H x 16"W per panel',
    color: 'Natural Bamboo',
    donorType: 'Student Donor',
    postedDate: '2025-03-23',
    expiryDate: '2025-04-23',
    tags: ['apartment', 'student-friendly'],
    views: 134,
    requests: 9,
    images: ['divider1'],
  },
  {
    id: '85',
    name: 'Can Opener + Kitchen Tools',
    category: 'Kitchen Items',
    condition: 'Good',
    description: 'Box of kitchen essentials: can opener, peeler, grater, measuring cups/spoons, cutting board.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: 'Box 12"x8"x6"',
    color: 'Mixed',
    donorType: 'Family Donor',
    postedDate: '2025-03-26',
    expiryDate: '2025-04-26',
    tags: ['apartment', 'student-friendly', 'compact', 'free', 'dorm-ready'],
    views: 78,
    requests: 6,
    images: ['kitchentools1'],
  },
  {
    id: '86',
    name: 'TV Stand',
    category: 'Storage',
    condition: 'Good',
    description: 'TV stand with 2 shelves and 2 cabinets. Espresso finish. Fits TVs up to 60".',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '60"W x 16"D x 24"H',
    color: 'Espresso',
    donorType: 'Family Donor',
    postedDate: '2025-03-15',
    expiryDate: '2025-04-15',
    tags: ['apartment', 'student-friendly'],
    views: 189,
    requests: 13,
    images: ['tvstand1'],
  },
  {
    id: '87',
    name: 'Outdoor Plant Pots (Set of 5)',
    category: 'Miscellaneous',
    condition: 'Like New',
    description: 'Set of 5 terracotta pots in various sizes. Perfect for indoor or outdoor plants.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '4" to 12" diameter',
    color: 'Terracotta',
    donorType: 'Faculty',
    postedDate: '2025-03-29',
    expiryDate: '2025-04-29',
    tags: ['apartment', 'compact', 'free'],
    views: 45,
    requests: 3,
    images: ['pots2'],
  },
  {
    id: '88',
    name: 'Portable Fan',
    category: 'Appliances',
    condition: 'Good',
    description: '20" box fan. 3 speeds. Works great. Quiet operation. Great for summer.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '20"W x 6"D x 20"H',
    color: 'White',
    donorType: 'Student Donor',
    postedDate: '2025-03-22',
    expiryDate: '2025-04-22',
    tags: ['dorm-ready', 'compact', 'student-friendly', 'free'],
    views: 223,
    requests: 17,
    images: ['boxfan1'],
  },
  {
    id: '89',
    name: 'Rolling Cart - 3 Tier',
    category: 'Storage',
    condition: 'Like New',
    description: 'Rose gold rolling storage cart with 3 mesh baskets. Perfect for art supplies or kitchen.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '12"W x 15"D x 27"H',
    color: 'Rose Gold',
    donorType: 'Student Donor',
    postedDate: '2025-03-28',
    expiryDate: '2025-04-28',
    tags: ['dorm-ready', 'compact', 'student-friendly', 'lightly-used'],
    views: 167,
    requests: 13,
    images: ['rollingcart1'],
  },
  {
    id: '90',
    name: 'College Dorm Bed Bundle',
    category: 'Beds',
    condition: 'Good',
    description: 'Complete dorm bundle: Twin XL bed frame, mattress topper, and 2 bed risers. All pieces included.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: 'Twin XL: 39"x80"',
    color: 'White/Grey',
    donorType: 'Student Donor',
    postedDate: '2025-03-20',
    expiryDate: '2025-04-20',
    tags: ['dorm-ready', 'student-friendly', 'free', 'compact'],
    views: 456,
    requests: 35,
    images: ['dormbundle1'],
  },
  {
    id: '91',
    name: 'Accent Table - Gold',
    category: 'Tables',
    condition: 'Like New',
    description: 'Gold metal accent table with marble top. 18" round. Statement piece for any room.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '18" diameter x 22"H',
    color: 'Gold/Marble',
    donorType: 'Faculty',
    postedDate: '2025-03-29',
    expiryDate: '2025-04-29',
    tags: ['apartment', 'lightly-used'],
    views: 123,
    requests: 9,
    images: ['accenttable1'],
  },
  {
    id: '92',
    name: 'Planner Whiteboard',
    category: 'Miscellaneous',
    condition: 'Like New',
    description: 'Monthly planner whiteboard with dry-erase markers. 24"x36". Magnetic.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '24"W x 36"H',
    color: 'White',
    donorType: 'Student Donor',
    postedDate: '2025-03-28',
    expiryDate: '2025-04-28',
    tags: ['dorm-ready', 'student-friendly', 'compact', 'free'],
    views: 167,
    requests: 13,
    images: ['whiteboard1'],
  },
  {
    id: '93',
    name: 'Bedside Lamp (Pair)',
    category: 'Lamps',
    condition: 'Good',
    description: 'Matching pair of ceramic bedside lamps. White with fabric shades. 18"H.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '6" base x 18"H',
    color: 'White',
    donorType: 'Community Member',
    postedDate: '2025-03-24',
    expiryDate: '2025-04-24',
    tags: ['apartment', 'compact', 'student-friendly'],
    views: 78,
    requests: 5,
    images: ['lamps1'],
  },
  {
    id: '94',
    name: 'Wooden Coat Rack',
    category: 'Miscellaneous',
    condition: 'Good',
    description: 'Freestanding wooden coat rack with 8 hooks. Umbrella stand at bottom. 72"H.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '16"W x 16"D x 72"H',
    color: 'Dark Brown',
    donorType: 'Family Donor',
    postedDate: '2025-03-17',
    expiryDate: '2025-04-17',
    tags: ['apartment', 'compact', 'student-friendly'],
    views: 89,
    requests: 6,
    images: ['coatrack1'],
  },
  {
    id: '95',
    name: 'Ping Pong Table',
    category: 'Miscellaneous',
    condition: 'Good',
    description: 'Full-size ping pong table. Folds in half for storage. Paddles and balls included.',
    location: LOCATIONS[1],
    availability: 'Available',
    pickupType: 'Scheduled',
    dimensions: '108"L x 60"W x 30"H',
    color: 'Green/Blue',
    donorType: 'Community Member',
    postedDate: '2025-03-10',
    expiryDate: '2025-04-10',
    tags: ['lightly-used', 'urgent-pickup'],
    views: 234,
    requests: 14,
    images: ['pingtable1'],
  },
  {
    id: '96',
    name: 'Portable Clothes Rack',
    category: 'Storage',
    condition: 'Good',
    description: 'Metal portable clothes rack. Adjustable height. Great for extra closet space in dorms.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: '35"W x 18"D x 66"H',
    color: 'Black',
    donorType: 'Student Donor',
    postedDate: '2025-03-25',
    expiryDate: '2025-04-25',
    tags: ['dorm-ready', 'compact', 'student-friendly', 'free'],
    views: 145,
    requests: 11,
    images: ['clothesrack1'],
  },
  {
    id: '97',
    name: 'Treadmill - Folding',
    category: 'Miscellaneous',
    condition: 'Good',
    description: 'Compact folding treadmill. Up to 7 mph. Heart rate monitor on handles. Good condition.',
    location: LOCATIONS[1],
    availability: 'Available',
    pickupType: 'Curbside',
    dimensions: '64"L x 27"W x 52"H (unfolded)',
    color: 'Black/Grey',
    donorType: 'Community Member',
    postedDate: '2025-03-09',
    expiryDate: '2025-04-09',
    tags: ['apartment', 'lightly-used', 'urgent-pickup'],
    views: 312,
    requests: 20,
    images: ['treadmill1'],
  },
  {
    id: '98',
    name: 'Window Air Conditioner',
    category: 'Appliances',
    condition: 'Good',
    description: '5000 BTU window AC unit. LG brand. Cools up to 150 sq ft. Works great.',
    location: LOCATIONS[1],
    availability: 'Available',
    pickupType: 'Scheduled',
    dimensions: '16"W x 15"D x 12"H',
    color: 'White',
    donorType: 'Family Donor',
    postedDate: '2025-03-12',
    expiryDate: '2025-04-12',
    tags: ['apartment', 'lightly-used'],
    views: 398,
    requests: 30,
    images: ['ac1'],
  },
  {
    id: '99',
    name: 'Board Games Collection',
    category: 'Toys',
    condition: 'Good',
    description: 'Assorted board games: Monopoly, Scrabble, Jenga, and more. All pieces included.',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: 'Box sizes vary',
    color: 'Various',
    donorType: 'Family Donor',
    postedDate: '2025-03-21',
    expiryDate: '2025-04-21',
    tags: ['compact', 'free', 'student-friendly', 'dorm-ready'],
    views: 134,
    requests: 10,
    images: ['boardgames1'],
  },
  {
    id: '100',
    name: 'Apartment Starter Kit',
    category: 'Miscellaneous',
    condition: 'Good',
    description: 'Complete apartment starter bundle: bath mats, shower curtain, hand towels, dish soap, sponges, and basic cleaning supplies. Everything you need to move in!',
    location: LOCATIONS[0],
    availability: 'Available',
    pickupType: 'Mission Arlington',
    dimensions: 'Large box',
    color: 'Various',
    donorType: 'Community Member',
    postedDate: '2025-03-30',
    expiryDate: '2025-04-30',
    tags: ['free', 'apartment', 'student-friendly', 'dorm-ready'],
    views: 512,
    requests: 41,
    images: ['starterkit1'],
  },
];

export default INVENTORY;
