kind = "mobile"
previewPath = "/"
title = "UTA FurniFind"
version = "1.0.0"
id = "artifacts/uta-furnifind"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 26249

[services.development]
run = "pnpm --filter @workspace/uta-furnifind run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/uta-furnifind", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/uta-furnifind", "run", "serve" ]

[services.env]
PORT = "26249"
BASE_PATH = "/"
